# **Topic 1: Numpy Basics**

In [43]:
import numpy as np

In [ ]:
# Initialize numpy array(explicitly).

a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [ ]:
a.ndim

1

In [ ]:
# Using arange method to initialize numpy array.

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Numpy is a memory efficient container that provides fast numerical operations.

# python list
L = range(1000)     # [0, 1, 2, 3...]
%timeit [i**2 for i in L]     # [0, 1, 4, 9...]
# timeit finds out the time taken per iteration of the fn

300 µs ± 3.28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# numpy implementation
a = np.arange(1000)
%timeit a**2

1.55 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# numpy implementation is ~200 times faster than list implementation

## **1.1 Creating arrays**

#### **1.1.1 Manual construction**

In [ ]:
# 1-d

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [ ]:
# print dimensions

a.ndim

1

In [ ]:
# shape

a.shape

(4,)

In [ ]:
# length

len(a)

4

In [ ]:
# 2-d, 3-d... arrays(Give a list of lists)
# numpy takes each list as row

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b) #gives size of the first dimension

2

In [ ]:
# 3-d(List within a list within a list)

c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
# 1-D array --> Vector
# 2-D array --> matrix
# n-D array --> Tensor

#### **1.1.2 Functions for creating arrays**

In [ ]:
# Using arange fn
# arange is an array-valued version of the built-in python range function

a = np.arange(10) # 0...n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 10, 2) #(start, end(exclusive), step)
b

array([1, 3, 5, 7, 9])

In [ ]:
# using linspace
# divides the space between start and step in n points

a = np.linspace(0, 1, 6) #(start, end, number of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# common arrays

b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3) # Returns identity 3x3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3, 2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# using diag fn

a = np.diag([1, 2, 3, 4]) #construct a diagnol array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)  # Extract diagnol

array([1, 2, 3, 4])

In [ ]:
# create array using random
a = np.random.rand(4) # Uniform random variable
a

# np --> package
# random --> sub package/module
# rand --> function

array([0.03241055, 0.76058975, 0.82208081, 0.2977766 ])

In [ ]:
a = np.random.randn(4) # Gaussian random variable
a

array([-1.25935596,  0.65662111,  0.43156028, -0.04070538])

## **1.2 Basic Data Types**

In [ ]:
# Trailing dots in array elements is due to difference in data type used

In [ ]:
a = np.arange(10)
a.dtype

dtype('int64')

In [ ]:
# Explicitly defining the required float

a = np.arange(10, dtype = "float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# The default dtype for zeros and ones is float

a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

### **1.2.1 Other data types**

In [ ]:
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [ ]:
b = np.array([True, False, True])
print(b.dtype)

bool


In [ ]:
s = np.array(['Ram', 'Robert', 'Shyam'])
s.dtype

dtype('<U6')

## **1.3 Indexing and Slicing**

### **1.3.1 Indexing**

In [ ]:
a = np.arange(10)
print(a[5])

5


In [ ]:
a = np.diag([1, 2, 3])
print(a[2, 2])      # row 2, col 2

3


In [ ]:
a[2, 1] = 5     # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

### **1.3.2 Slicing**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2]    # [startindex: endindex(exclusive): step]

array([1, 3, 5, 7])

In [ ]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1] # assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## 1.4 **Copies and Views**

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the orignial array is not copies into memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modified as well.

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a # even though we modified b, a also changed because a and b both point to same location in memory which is a property of slicing

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
c = a[::2].copy() # force a copy
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, c)

False

In [ ]:
c[0] = 10
c

array([10,  2,  4,  6,  8])

In [ ]:
a # No more memory sharing due to copy functions

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **1.5 Fancy Indexing**

Numpy arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. It creates copies not views.

### **1.5.1 Using Boolean Masks**

In [ ]:
a = np.random.randint(0, 20, 15)
a

array([ 6, 16,  2, 15,  6, 19, 19,  9, 12, 17, 13, 15,  7,  3, 10])

In [ ]:
mask = (a % 2 == 0)

In [ ]:
extract_from_a = a[mask]
extract_from_a

array([ 6, 16,  2,  6, 12, 10])

In [ ]:
# Indexing with a mask can be very useful to assign a new value to a sub-array:

a[mask] = -1
a   # all even numbers become equal to -1

array([ 9,  1, -1, -1, -1,  9, -1,  7, 17, -1,  7, -1, -1,  1, -1])

In [ ]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Indexing can be done with an array of integers, where the same index is reused

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned

a[[9, 7]] = -200
a

array([   6,   16,    2,   15,    6,   19,   19, -200,   12, -200,   13,
         15,    7,    3,   10])

# **Topic 2: Numerical Operations on Numpy**

## **2.1 Elementwise Operations**

#### **2.1.1 With Scalers**

In [ ]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [ ]:
a - b

array([-1.,  0.,  1.,  2.])

In [ ]:
a * b

array([2., 4., 6., 8.])

In [ ]:
# Matrix multiplication

c = np.diag([1, 2, 3, 4])
print(c * c)
print('*****************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


#### **2.1.2 Comparisons**

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [ ]:
a > b

array([False, False,  True, False])

In [ ]:
# array wise comparisons
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

np.array_equal(a, b)

False

In [ ]:
np.array_equal(a, c)

True

#### **2.1.3 Logical Operations**

In [ ]:
a = np.array([1, 1, 0, 0], dtype = bool)
b = np.array([1, 0, 1, 0], dtype = bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [ ]:
np.logical_and(a, b)

array([ True, False, False, False])

#### **2.1.4 Transcendental functions**

In [ ]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.log(a)

<ipython-input-20-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
np.exp(a) # exvaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

#### **2.1.5 Shape Mismatch**

In [ ]:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## **2.2 Basic Reductions**

#### **2.2.1 Computing Sums**

In [ ]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [ ]:
# sum by rows and by columns

x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [ ]:
x.sum(axis = 0) # col wise sum

array([3, 3])

In [ ]:
x.sum(axis = 1) # row wise sum

array([2, 4])

#### **2.2.2 Other Reductions**

In [ ]:
x = np.array([1, 3, 2])
x.min()

1

In [ ]:
x.max()

3

In [ ]:
x.argmin() # index of min element

0

In [ ]:
x.argmax() # index of max element

1

#### **2.2.3 Logical Operations**

In [ ]:
# logical AND
np.all([True, True, False])

False

In [ ]:
# logical OR
np.any([True, False, False])

True

In [ ]:
# Note: can be used for array comparisons
a = np.zeros((50, 50))
np.any(a != 0)

False

In [ ]:
np.all(a == a)

True

In [ ]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

#### **2.2.4 Statistics**

In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [ ]:
np.median(x)

1.5

In [ ]:
np.median(y, axis = -1) #last axis i.e. row wise

array([2., 5.])

In [ ]:
x.std() # full population standard deviation

0.82915619758885

In [ ]:
# load data into numpy array object
data = np.loadtxt('Filename.txt')

## **2.3 Broadcasting**

Basic operations on numpy arrays(addition, etc.) are elementwise.

This works on arrays of the same size. Nevertheless, its also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

In [ ]:
# (3, 1) --> Replicate the numpy array 3 times row wise and 1 time column wise
# tile --> piling up off tiles

a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

print("***********************")

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
***********************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [ ]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
a = np.arange(0, 40, 10)
print(a.shape)
a

(4,)


array([ 0, 10, 20, 30])

In [ ]:
# Very Very Important

a = a[:, np.newaxis] # adds a new axis --> 2-D array
print(a.shape)
a

(4, 1)


array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## **2.4 Array Shape Manipulation**

#### **2.4.1 Flattening**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel() # Return a contiguous flattened array.
# Return 2-D matrix into a 1-D array

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

#### **2.4.2 Reshaping**

In [ ]:
# Inverse of flattening

In [ ]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [ ]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [ ]:
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b[0, 0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [ ]:
# Numpy wants to optimize memory hence the result
# Note: reshape may also return a copy

In [ ]:
a = np.zeros((3, 2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### **2.4.3 Adding a dimension**

Indexing with the np.newaxis object allows us to add an axis to an array.

Newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array
2D array will become 3D array
3D array will become 4D array and so on

In [44]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [45]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

#### **2.4.4 Dimension Shuffling**

In [50]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape

(4, 3, 2)

In [52]:
# 4 x 3 x 2 --> 3D array with 4 matrices with each matrix of size 3 x 2
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [53]:
a[0, 2, 1]

5

#### **2.4.5 Resizing**

In [60]:
a = np.arange(4)
a.resize((8, ))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [62]:
# However, it must not be referred to somewhere else:

b = a
a.resize((4, ))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

#### **2.4.6 Sorting Data**

In [66]:
# Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
b = np.sort(a, axis = 1)
b

[[5 4 6]
 [2 3 2]]


array([[4, 5, 6],
       [2, 2, 3]])

In [67]:
# inplace sort
a.sort(axis = 1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [69]:
# sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j # return indices

array([2, 3, 1, 0])

In [70]:
a[j]

array([1, 2, 3, 4])