# T**opic 1: Numpy**

In [3]:
import numpy as np

In [ ]:
# Initialize numpy array(explicitly).

a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [ ]:
a.ndim

1

In [ ]:
# Using arange method to initialize numpy array.

print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Numpy is a memory efficient container that provides fast numerical operations.

# python list
L = range(1000)     # [0, 1, 2, 3...]
%timeit [i**2 for i in L]     # [0, 1, 4, 9...]
# timeit finds out the time taken per iteration of the fn

300 µs ± 3.28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# numpy implementation
a = np.arange(1000)
%timeit a**2

1.55 µs ± 338 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [ ]:
# numpy implementation is ~200 times faster than list implementation

## **1.1 Creating arrays**

##### **1.1.1 Manual construction**

In [ ]:
# 1-d

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [ ]:
# print dimensions

a.ndim

1

In [ ]:
# shape

a.shape

(4,)

In [ ]:
# length

len(a)

4

In [ ]:
# 2-d, 3-d... arrays(Give a list of lists)
# numpy takes each list as row

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(2, 3)

In [ ]:
len(b) #gives size of the first dimension

2

In [ ]:
# 3-d(List within a list within a list)

c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
c.ndim

3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
# 1-D array --> Vector
# 2-D array --> matrix
# n-D array --> Tensor

#### **1.1.2 Functions for creating arrays**

In [ ]:
# Using arange fn
# arange is an array-valued version of the built-in python range function

a = np.arange(10) # 0...n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1, 10, 2) #(start, end(exclusive), step)
b

array([1, 3, 5, 7, 9])

In [ ]:
# using linspace
# divides the space between start and step in n points

a = np.linspace(0, 1, 6) #(start, end, number of points)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# common arrays

b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.eye(3) # Returns identity 3x3 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a = np.eye(3, 2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# using diag fn

a = np.diag([1, 2, 3, 4]) #construct a diagnol array
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)  # Extract diagnol

array([1, 2, 3, 4])

In [ ]:
# create array using random
a = np.random.rand(4) # Uniform random variable
a

# np --> package
# random --> sub package/module
# rand --> function

array([0.03241055, 0.76058975, 0.82208081, 0.2977766 ])

In [ ]:
a = np.random.randn(4) # Gaussian random variable
a

array([-1.25935596,  0.65662111,  0.43156028, -0.04070538])

## **1.2 Basic Data Types**

In [ ]:
# Trailing dots in array elements is due to difference in data type used

In [ ]:
a = np.arange(10)
a.dtype

dtype('int64')

In [ ]:
# Explicitly defining the required float

a = np.arange(10, dtype = "float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
# The default dtype for zeros and ones is float

a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

### **1.2.1 Other data types**

In [5]:
d = np.array([1+2j, 2+4j])
print(d.dtype)

complex128


In [6]:
b = np.array([True, False, True])
print(b.dtype)

bool


In [8]:
s = np.array(['Ram', 'Robert', 'Shyam'])
s.dtype

dtype('<U6')

## **1.3 Indexing and Slicing**

### **1.3.1 Indexing**

In [9]:
a = np.arange(10)
print(a[5])

5


In [10]:
a = np.diag([1, 2, 3])
print(a[2, 2])      # row 2, col 2

3


In [12]:
a[2, 1] = 5     # assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

### **1.3.2 Slicing**

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[1:8:2]    # [startindex: endindex(exclusive): step]

array([1, 3, 5, 7])

In [15]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [16]:
b = np.arange(5)
a[5:] = b[::-1] # assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

## 1.4 **Copies and Views**

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the orignial array is not copies into memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modified as well.

In [17]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [19]:
np.shares_memory(a, b)

True

In [20]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [22]:
a # even though we modified b, a also changed because a and b both point to same location in memory which is a property of slicing

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [23]:
a = np.arange(10)
c = a[::2].copy() # force a copy
c

array([0, 2, 4, 6, 8])

In [24]:
np.shares_memory(a, c)

False

In [26]:
c[0] = 10
c

array([10,  2,  4,  6,  8])

In [28]:
a # No more memory sharing due to copy functions

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **1.5 Fancy Indexing**

Numpy arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. It creates copies not views.

### **1.5.1 Using Boolean Masks**

In [38]:
a = np.random.randint(0, 20, 15)
a

array([ 6, 16,  2, 15,  6, 19, 19,  9, 12, 17, 13, 15,  7,  3, 10])

In [39]:
mask = (a % 2 == 0)

In [40]:
extract_from_a = a[mask]
extract_from_a

array([ 6, 16,  2,  6, 12, 10])

In [33]:
# Indexing with a mask can be very useful to assign a new value to a sub-array:

a[mask] = -1
a   # all even numbers become equal to -1

array([ 9,  1, -1, -1, -1,  9, -1,  7, 17, -1,  7, -1, -1,  1, -1])

In [34]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
# Indexing can be done with an array of integers, where the same index is reused

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [41]:
# New values can be assigned

a[[9, 7]] = -200
a

array([   6,   16,    2,   15,    6,   19,   19, -200,   12, -200,   13,
         15,    7,    3,   10])